[package]
name = "uk-ch-uri-rust"
version = "0.1.0"
authors = ["Arjan van Eersel <arjan@dbabs.com>"]

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
serde = "1.0.54"
serde_json = "1.0.17"
serde_derive = "1.0.54"
reqwest = "0.8.5"